[package]
name = "mathlang"
version = "0.1.0"
authors = ["Sean Hellum <seanhellum45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bignumber = "0.0.14"
regex = "0.2"
structopt = "0.3.7"
